# Generated by Django 3.0.8 on 2020-11-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taikhoan',
            fields=[
                ('matk', models.AutoField(db_column='MaTK', primary_key=True, serialize=False)),
                ('hoten', models.CharField(db_column='HoTen', max_length=70)),
                ('diachi', models.CharField(blank=True, db_column='DiaChi', max_length=200, null=True)),
                ('sodienthoai', models.CharField(blank=True, db_column='SoDienThoai', max_length=15, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('isadmin', models.IntegerField(blank=True, db_column='isAdmin', null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'taikhoan',
                'managed': False,
            },
        ),
    ]
