# Generated by Django 3.0.8 on 2020-11-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donhang',
            fields=[
                ('madh', models.AutoField(db_column='MaDH', primary_key=True, serialize=False)),
                ('thoigiandathang', models.DateTimeField(auto_now_add=True, db_column='ThoiGianDatHang')),
                ('trangthai', models.IntegerField(blank=True, db_column='TrangThai', default=0, null=True)),
            ],
            options={
                'db_table': 'donhang',
                'managed': False,
            },
        ),
    ]
