# Generated by Django 3.0.8 on 2020-11-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chitietdonhang',
            fields=[
                ('machitiet', models.AutoField(db_column='MaChiTiet', primary_key=True, serialize=False)),
                ('soluong', models.IntegerField(db_column='SoLuong')),
                ('giadathang', models.DecimalField(blank=True, db_column='GiaDatHang', decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'chitietdonhang',
                'managed': False,
            },
        ),
    ]
