# Generated by Django 3.0.8 on 2020-11-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hanghoa',
            fields=[
                ('mahh', models.AutoField(db_column='MaHH', primary_key=True, serialize=False)),
                ('ten', models.CharField(db_column='Ten', max_length=100)),
                ('hinhanh', models.FileField(blank=True, db_column='HinhAnh', null=True, upload_to='')),
                ('mota', models.CharField(blank=True, db_column='MoTa', max_length=1000, null=True)),
                ('gia', models.DecimalField(db_column='Gia', decimal_places=0, max_digits=10)),
                ('soluong', models.IntegerField(blank=True, db_column='SoLuong', null=True)),
            ],
            options={
                'db_table': 'hanghoa',
                'managed': False,
            },
        ),
    ]
